# Generated by Django 3.0.2 on 2020-03-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_auto_20200302_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='from_user',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
