# Generated by Django 3.0.2 on 2020-03-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20200302_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='to_user',
            new_name='from_user',
        ),
    ]
