# Generated by Django 3.0.2 on 2020-03-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0013_auto_20200305_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listed_items',
            new_name='listed_item',
        ),
    ]
