# Generated by Django 3.0.2 on 2020-03-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0014_auto_20200305_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
    ]
