# Generated by Django 3.0.2 on 2020-03-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_buyer'),
        ('jwt_auth', '0019_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='items.Item'),
        ),
    ]
