# Generated by Django 3.0.2 on 2020-03-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0021_remove_user_listed_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
