# Generated by Django 3.0.2 on 2020-03-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200309_1307'),
        ('jwt_auth', '0023_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='baskets', to='items.Item'),
        ),
    ]
