# Generated by Django 3.0.2 on 2020-03-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0024_auto_20200310_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
