# Generated by Django 3.0.2 on 2020-01-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categories',
        ),
    ]
