# Generated by Django 3.0.2 on 2020-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200125_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer',
            field=models.CharField(default='', max_length=500),
        ),
    ]
