# Generated by Django 3.0.2 on 2020-03-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
    ]
