# Generated by Django 3.0.2 on 2020-03-10 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
