# Generated by Django 3.0.2 on 2020-02-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0005_item_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_posted', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile', to='items.Item')),
            ],
        ),
    ]
